apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
      nodePort: 30005
